title: Docs
description: Test
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Sid Reid
repo_url: "https://github.com/NightSid3r/BrisDASAR"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
