title: Docs
description: Test
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Sid Reid
repo_url: "https://github.com/NightSid3r/BrisDASAR"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
search_enabled: true
logo: 'https://raw.githubusercontent.com/NightSid3r/BrisDASAR/main/docs/BrisDASAR.png'
site_favicon: 'https://raw.githubusercontent.com/NightSid3r/BrisDASAR/main/docs/BrisDASAR.ico'
prev_next_buttons_location: None
prev_next_buttons_location: top
prev_next_buttons_location: bottom
prev_next_buttons_location: both
google_analytics: UA-XXXXX-Y
google_analytics_anonymize_ip: true
# The highlight.js library provides 79 different colours for their syntax highlighting. The default is github-gist.
hljs_style: github-gist
